#- name: delete old server.xml
#  file: path=/home/java/tomcat7_8081/conf/server.xml state=absent
- name: copy server_template.xml as server.xml
  template: src=server_template.xml  dest=/home/java/tomcat7_8081/conf/server.xml

#- name: delete old config server.xml
#  shell: sed -i '/--{{appname}}-Conf-Start/,/--{{appname}}-Conf-End/d' /home/java/tomcat7_8081/conf/server.xml

#- name: config server.xml
#  shell: sed -i '/<\/Realm>/r /home/java/server_template.xml' /home/java/tomcat7_8081/conf/server.xml
#- name: delete config context.xml
#  file: path=/home/java/tomcat7_8081/conf/context.xml state=absent
- name: copy context_template.xml as context.xml
  template: src=context_template.xml dest=/home/java/tomcat7_8081/conf/context.xml

#- name: delete old config context.xml
#  shell: sed -i '/--{{appname}}-Conf-Start/,/--{{appname}}-Conf-End/d'  /home/java/tomcat7_8081/conf/context.xml

#- name: config defaultHost
#  shell: sed -i '/<Context>/r /home/java/context_template.xml' /home/java/tomcat7_8081/conf/context.xml

#- name: delete context_template.xml
#  file: path=/home/java/context_template.xml state=absent

#- name: delete server_template.xml
#  file: path=/home/java/server_template.xml state=absent


