---

- name: rm hosts.war
  file: path=~/{{hosts}}.war state=absent

- name: copycheckfile
  copy: src=/etc/ansible/files/checkstartup.sh dest=/home/java/checkstartup.sh mode=755
- template: src=/etc/ansible/files/chkhealth.sh dest=/home/java/chkhealth.sh mode=755

- name: start tomcat
  shell: nohup /home/java/starttomcat.sh

- name: tomcat startup?
  shell: /home/java/checkstartup.sh

#- name: 服务是否正常?
#  shell: /home/java/chkhealth.sh

- name: delete nouse files
  file: path=/home/java/{{item}} state=absent
  with_items:
    - dubbo
    - server_template.xml
    - context_template.xml

