# update war
#- name: copy war
  #copy: src=/etc/ansible/roles/deploy/files/{{hosts}}_{{env}}.war dest=/home/java/{{hosts}}.war mode=0755
#  copy: src=/etc/ansible/war/{{hosts}}_{{env}}.war dest=/home/java/{{hosts}}.war mode=0755

#- name: war directory
#  file: path=/home/webapp/{{hosts}} state=directory


- name: rm bakdirectory
  file: path=/home/webapp/{{hosts}}.bak state=absent
#- name: bak directory
#  file: path=/home/webapp/{{hosts}}.bak state=directory
#
#- name: war directory
#  file: path=/home/webapp/{{hosts}} state=directory

- name: copy bak project
  copy: src=../../script/bak_project.py dest=/home/java/bak_project.py mode=755

- name: bak project
  shell: nohup /home/java/bak_project.py {{hosts}}

#- name: copy old war
#  shell: \cp -a /home/webapp/{{hosts}} /home/webapp/{{hosts}}.bak
#  register: result
#  ignore_errors: True

- name: delete old war  
  file: path=/home/webapp/{{hosts}}/ state=absent
- name: war directory
  file: path=/home/webapp/{{hosts}} state=directory

- name: tar new war
  unarchive: src=/data/war/{{hosts}}/{{hosts}}_{{env}}.war dest=/home/webapp/{{hosts}}

#- name: unzip war
#  shell: unzip {{hosts}}.war -d /home/webapp/{{hosts}}



